### ISSUE TITLE
Yanp_feedlink broken on case-sensitive file systems

### ISSUE THREAD

**Issue by BillyV2018** [cmb69/yanp_xh#13]
The Yanp 2.0 module Yanp_feedlink throws an error.

My installation is, all unmodified modules:
CMSimple_XH 1.7.4  Released: 2020-10-26

Installed Plugins
Fa 1.3
Feedview 1.0beta1
Filebrowser for CMSimple_XH 1.7.4
Flexslider 0.5.5
Hi_updatecheck 1.4
Jquery 1.6.5
Meta_tags for CMSimple_XH 1.7.4
Pagemanager 3.6
Page_params for CMSimple_XH 1.7.4
Tinymce4 1.3.4 - 2020-08-21
Yanp 2.0
Webserver Apache/2.4.38 (Debian)
PHP-Version 7.3.27-1~deb10u1

I use the latest available version of Yanp, if I am not mistaken.
In a previous version 1pl5 I called in a newsbox the module {{{Yanp_feedlink()}} without problem.
In the present version 2.0 I try to use the same, but it throws an error (XH debug mode is on):

````
Uncaught Error: Class 'Yanp\FeedlinkCommand' not found in /home/etcetera/htdocs/new-rkspa/plugins/yanp/classes/Plugin.php:113
Stack trace:
#0 /home/etcetera/htdocs/new-rkspa/plugins/yanp/classes/Plugin.php(98) : eval()'d code(2): Yanp\Plugin::feedlinkCommand(NULL)
#1 /home/etcetera/htdocs/new-rkspa/cmsimple/functions.php(242) : eval()'d code(1): yanp_feedlink()
#2 /home/etcetera/htdocs/new-rkspa/cmsimple/functions.php(242): eval()
#3 /home/etcetera/htdocs/new-rkspa/cmsimple/functions.php(202): XH_evaluateSinglePluginCall('Yanp_feedlink()')
#4 /home/etcetera/htdocs/new-rkspa/cmsimple/functions.php(299): evaluate_plugincall('#CMSimple hide#...')
#5 /home/etcetera/htdocs/new-rkspa/cmsimple/cms.php(1287): evaluate_scripting('#CMSimple hide#...')
#6 /home/etcetera/htdocs/new-rkspa/index.php(6): include('/home/etcetera...')
#7 {main}
thrown in /home/etcetera/htdocs/new-rkspa/plugins/yanp/classes/Plugin.php on line 113
````

NB the Yanp_newsbox is also used on a different page as {{{Yanp_newsbox}}} and has no problem.

**Comment by cmb69** [comment]
D'oh! The file is called `FeedLinkCommand.php`, but the class `FeedlinkCommand` – the `L` is uppercase in the filename, but lower-case in the classname, and that won't work on case-sensitive file systems.
